# Generated by Django 5.0.6 on 2024-05-31 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_tag_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
    ]
